### PR TITLE
New rotate sync example

### PR DESCRIPTION
**Pull request by Linskeyd**
#34 here https://github.com/Famous/examples/pull/34#issuecomment-43007652

Added as a separate file in the RotateSync folder.

### CODE REVIEW

**Comment by michaelobriena** [comment]
I can dig it.  @TheAlphaNerd.

**Comment by MylesBorins** [comment]
hey @Linskeyd can you move this to famous/famous referencing this issue?

**Comment by Linskeyd** [comment]
By move this do you mean just post an issue in famous/famous referencing this?

**Comment by MylesBorins** [comment]
More specifically recreate this patch on the new flattened repo and send the pull request to famous/famous

We have deprecated the submodules

**Comment by Linskeyd** [comment]
Sorry I'm not sure that would apply to this.  This was just a example addition to an already existing example in the example repo (lot of examples lol).  All this did was instead of just displaying the rotation values in the example, it also rotated a surface with a StateModifier.  This in no way modifies the RotateSync code on the main repo.  If this submodule has been deprecated then I can close this out.

**Comment by MylesBorins** [comment]
My mistake... This got caught up in a round of other commit updates.

**Comment by MylesBorins** [comment]
@michaelobriena can you close this?

**Pull request closed without merging**
