### PR TITLE
update git modules to point to http instead of git

### PR DESCRIPTION
**Pull request by MylesBorins**
This solves #28  and #25 more elegantly

I also think it might be worth switching this repo over to the new project formate... it would be possible to make a grunt task to automate switching between examples.

### CODE REVIEW

**Comment by jedihe** [comment]
I remember testing in my fork doing that... but when checking out the internal submodules, I had the same issue: "Permission denied (publickey)". So, this change should be done in the famous repo too.

Are you able to test both the wrong and fixed states?

**Comment by MylesBorins** [comment]
@jedihe You are totally right!  Sorry I glazed over that.  I ended up changing the version of famous that things are being pointed to.  It now points at the flattened branch, which should solve this entire problem

**Comment by dmvaldman** [comment]
Can we have the src/famous track master?

**Comment by MylesBorins** [comment]
Yup,  we just need to make sure it is pointing to httpnot git

**Comment by MylesBorins** [comment]
And also make sure it is pointing to the commit with httpin the main repo
git modules

**Comment by MylesBorins** [comment]
Closing and going to make a new pull request

**Pull request closed without merging**
