### PR TITLE
updating famous to master

### PR DESCRIPTION
**Pull request by timjchin**
@TheAlphaNerd 
Updated famous submodule to famous/famous master.

### CODE REVIEW

**Comment by MylesBorins** [comment]
@michaelobriena can you review this?

**Comment by michaelobriena** [comment]
Can we make this use npm and not git submodules?

**Comment by MylesBorins** [comment]
I think that will be a slightly bigger refactor that involves tooling (browserify setup).  I suggest we pull this and then I can work on implementing the common stuff.

**Comment by michaelobriena** [comment]
This is cool with me.  I think that this needs to be tagged with a version and should be done every single minor version bump.

**Comment by MylesBorins** [comment]
I agree.  Train is just pulling in.  See ya in a minute

**Pull request closed without merging**
