### PR TITLE
Updated README fixes #25

### LINKED ISSUE #25: no clone
Permission denied (publickey).
fatal: Could not read from remote repository.

### PR DESCRIPTION
**Pull request by fczuardi**
to use the read-only version in the cloning example

### CODE REVIEW

**Comment by fczuardi** [comment]
the cloning thing is a real issue, changint to http didnt fix this, closing the PR

**Comment by dmvaldman** [comment]
I'm surprised it didn't fix the problem. What was wrong?

**Comment by tvararu** [comment]
Perhaps lack of public key configuration, as in [examples#27](https://github.com/Famous/examples/issues/27). Cloning with recursive does use SSH whether you like it or not, from the looks of it.

**Comment by MylesBorins** [comment]
You need to add http+ssh

**Comment by MylesBorins** [comment]
#31 also solves this problem

**Pull request closed without merging**
